### ISSUE TITLE
"Copy python import statement" command does not work before "Copy python path" usage

### ISSUE THREAD

**Issue by otemek** [kawamataryo/copy-python-path#3]
"Copy python import statement" command does not work if used before "Copy python path" command.

If this command as a first is selected from the right-mouse button click - nothing appears (no any info message at the right bottom)
If this command as a first is select from the command pallete
![2022-10-03 10_17_22-Window](https://user-images.githubusercontent.com/3636875/193533496-d1e9ccf8-dc41-424d-bcbd-a3bf972accb2.png)
then the error message appears:
![2022-10-03 10_17_37-Window](https://user-images.githubusercontent.com/3636875/193533024-1dc29fa5-7400-460a-b5ab-3231e6c143c3.png)

If I first select (either from command pallete, or right mouse click dropdown menu)  "Copy python path" and then "Copy python import statement" then it works...
Any chances to fix it so "copy python import statement" works without "copy python path" as first?

**Comment by kawamataryo** [comment]
@otemek 

Thanks for the issue.
I didn't know this bug. I try fix it.

Please wait few days.
